# Generated by Django 4.1.2 on 2022-10-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engraving',
            name='author',
            field=models.ManyToManyField(blank=True, default=None, to='museum.author'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='author',
            field=models.ManyToManyField(blank=True, default=None, to='museum.author'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='engraving',
            field=models.ManyToManyField(blank=True, default=None, to='museum.engraving'),
        ),
    ]
