# Generated by Django 4.1.2 on 2022-10-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0005_author_biography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
