# Generated by Django 4.1.2 on 2022-10-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0006_alter_painting_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='engraving',
            name='cover',
            field=models.ImageField(default='a', upload_to='engravings/cover/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
