# Generated by Django 4.1.2 on 2022-10-31 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0007_engraving_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='is_engraving',
            field=models.BooleanField(default=False),
        ),
    ]
