# Generated by Django 4.1.2 on 2022-11-16 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0008_author_is_engraving'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='church',
            table='CHURCH',
        ),
        migrations.AlterModelTable(
            name='engraving',
            table='ENGRAVING',
        ),
        migrations.AlterModelTable(
            name='painting',
            table='PAINTING',
        ),
    ]
