# Generated by Django 4.1.2 on 2022-11-16 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0009_alter_church_table_alter_engraving_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='author',
            table='AUTHOR',
        ),
    ]
