# Generated by Django 4.1.2 on 2022-11-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0002_alter_tag_table'),
        ('museum', '0011_alter_painting_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='tag',
            field=models.ManyToManyField(blank=True, default=None, to='tag.tag'),
        ),
    ]
