# Generated by Django 4.1.2 on 2022-11-17 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tag',
            table='TAG',
        ),
    ]
